"""Autogenerated Hugging Face dataset card (README.md) renderer.

The card is built from metadata that the export script gathers from the actual
generated records (schema, splits, source counts) plus configuration
(sources, severity scale, corruption types).
"""

import json
import os

_SIZE_CATEGORIES = (
    ("n<1K", 0, 1000), ("1K<n<10K", 1000, 10000), ("10K<n<100K", 10000, 100000),
    ("100K<n<1M", 100000, 1000000), ("1M<n<10M", 1000000, 10000000),
    ("10M<n<100M", 10000000, 100000000), ("100M<n<1B", 100000000, 1000000000),
    ("1B<n<10B", 1000000000, 10000000000), ("n>1B", 10000000000, None),
)


def _size_category(total):
    for label, lo, hi in _SIZE_CATEGORIES:
        if total >= lo and (hi is None or total < hi):
            return label
    return "n<1K"


def _frontmatter(meta):
    categories = [meta.get("task_category", "other")]

    def _languages():
        langs = meta.get("languages") or ["en"]
        return "\n".join(f"  - {lang}" for lang in langs)

    def _tags():
        tags = ["terrupt"] + (meta.get("tags") or [])
        return "\n".join(f"  - {tag}" for tag in tags)

    def _features():
        lines = []
        for field in meta.get("schema", []):
            lines.append(f"  - name: {field['name']}\n    dtype: {field['dtype']}")
        return "\n".join(lines)

    def _splits():
        lines = []
        for name, count in (meta.get("splits") or {}).items():
            lines.append(f"  - name: {name}\n    num_examples: {count}")
        return "\n".join(lines)

    total = sum((meta.get("splits") or {}).values())
    return f"""---
language:
{_languages()}
license: {meta.get("license", "mit")}
size_categories:
- {_size_category(total)}
task_categories:
{''.join(f'- {c}\n' for c in categories).rstrip()}
tags:
{_tags()}
dataset_info:
  features:
{_features()}
  splits:
{_splits()}
---"""


def _source_table(meta):
    rows = ["| Source | Config | Sentences | Status |",
            "|--------|--------|-----------|--------|"]
    for src in meta.get("sources", []):
        config = src.get("config") or "default"
        rows.append(
            f"| [{src['hf_id']}](https://huggingface.co/datasets/{src['hf_id']}) "
            f"({src['name']}) | `{config}` | {src.get('sentences', '-')} | "
            f"{src.get('status', '-')} |"
        )
    return "\n".join(rows)


def _corruption_table(meta):
    rows = ["| Corruption type | Description |", "|-----------------|-------------|"]
    for op in meta.get("corruption_types", []):
        rows.append(f"| `{op['name']}` | {op['description']} |")
    return "\n".join(rows)


def _schema_table(meta):
    rows = ["| Field | Type |", "|-------|------|"]
    for field in meta.get("schema", []):
        rows.append(f"| `{field['name']}` | {field['dtype']} |")
    return "\n".join(rows)


def _splits_table(meta):
    rows = ["| Split | Examples |", "|-------|----------|"]
    for name, count in (meta.get("splits") or {}).items():
        rows.append(f"| {name} | {count} |")
    return "\n".join(rows)


def _sources_json(meta):
    return json.dumps(meta.get("sources", []), indent=2, ensure_ascii=False)


def render_card(meta):
    """Render a complete dataset card markdown document."""
    task = meta.get("task", "unknown")
    severities = ", ".join(str(s) for s in meta.get("severities", []))
    return f"""{_frontmatter(meta)}

# {meta['name']}

> Auto-generated dataset card. Terrupt — dataset + benchmark for restoring
> intentionally corrupted text.

## Dataset Summary

{meta.get('description', 'Synthetic dataset of intentionally corrupted natural language.')}

## Task

**{meta.get('task_title', task)}** ({task})

The model receives corrupted text and must recover the original:

| Input | Target |
|-------|--------|
| `{meta.get('example_input', 'i l0ve pr0gramm1ng')}` | `{meta.get('example_target', 'I love programming')}` |

## Source Corpora

The sentences used as corruption bases were sampled from the following Hugging
Face datasets. Each source is streamed, cleaned, and split into sentences
before corruption is applied.

{_source_table(meta)}

Source usage in the generated records:

```json
{_sources_json(meta)}
```

## Corruption Engine

The corruption engine applies one or more atomic operations to a clean
sentence. Severity controls both how many operations run and how aggressive
each one is.

{_corruption_table(meta)}

**Severity scale:** {meta.get('severity_scale', '')}

**Severity levels in this dataset:** {severities or 'all'}

## Dataset Structure

### Schema

{_schema_table(meta)}

### Splits

{_splits_table(meta)}

## Usage

```python
from datasets import load_from_disk

ds = load_from_disk("./{os.path.basename(meta['out_dir'])}")
print(ds["train"][0])
```

Or push it to the Hub to get a browsable dataset view:

```python
ds.push_to_hub("your-org/{meta['name']}")
```

## Generation

{json.dumps(meta.get('generation', {}), indent=2, ensure_ascii=False)}

## Limitations

The corruption operations are keyboard-oriented for Latin scripts
(leetspeak, keyboard typos, homoglyphs); other scripts receive char-level
corruptions. Records are synthetic, so distributional shifts relative to
real-world typos are possible.

## License

{meta.get('license', 'mit')}
"""


def build_meta(args, stats, schema, sources, corruption_types, example, language):
    """Assemble card metadata from CLI args, record stats, and source info."""
    total = sum(stats.get("splits", {}).values())
    return {
        "name": args.name,
        "out_dir": args.out,
        "description": args.description,
        "task": args.task,
        "task_title": args.task_title,
        "task_category": args.task_category,
        "tags": args.tags.split(",") if args.tags else [],
        "license": args.license,
        "languages": [language],
        "sources": sources,
        "corruption_types": corruption_types,
        "severities": args.severities,
        "severity_scale": args.severity_scale,
        "splits": stats.get("splits", {}),
        "schema": schema,
        "generation": {
            "seed": args.seed,
            "count": total,
            "per_source": "unlimited" if (args.per_source or 0) <= 0 else args.per_source,
            "wikipedia_config": args.wikipedia_config,
            "modes": args.modes,
            "include_clean": args.include_clean,
        },
        "example_input": example[0],
        "example_target": example[1],
        "version": args.version,
        "date": args.date,
    }
